### ISSUE TITLE
Fix bug in estimation task

### ISSUE THREAD

**Issue by tsalo** [NBCLab/localizer-task#6]
I'm not sure what's causing this bug, but here's what I got when running the task on my Mac, after 6/10 trials of each of the conditions (evenly split probably by luck):

```
psy2723:localizer-task tsalo$ python estimation_task.py 
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
1.7164 	INFO 	Loaded SoundDevice with PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
1.7166 	INFO 	sound is using audioLib: sounddevice
1.7174 	INFO 	Loaded monitor calibration from ['2018_09_21 09:35']
3.6534 	DATA 	Mouse: Left button down, pos=(295,300)
3.7590 	DATA 	Mouse:  Left button up, pos=(295,300)
4.4247 	WARNING 	Couldn't measure a consistent frame rate.
  - Is your graphics card set to sync to vertical blank?
  - Are you running other processes on your computer?

4.4253 	EXP 	Created window1 = Window(allowGUI=True, allowStencil=False, args=UNKNOWN, autoLog=True, bitsMode=UNKNOWN, blendMode='avg', color=array([0., 0., 0.]), colorSpace='rgb', fullscr=UNKNOWN, gamma=None, kwargs=UNKNOWN, lms=UNKNOWN, monitor=<psychopy.monitors.calibTools.Monitor object at 0x10bd877b8>, multiSample=False, name='window1', numSamples=2, pos=[240.0, 100.0], screen=0, size=array([1600, 1200]), stereo=False, units='deg', useFBO=False, useRetina=True, viewOri=0.0, viewPos=None, viewScale=None, waitBlanking=True, winType='pyglet')
4.5350 	EXP 	Created unnamed TextStim = TextStim(__class__=<class 'psychopy.visual.text.TextStim'>, alignHoriz='center', alignVert='center', antialias=True, autoLog=True, bold=False, color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, flipHoriz=False, flipVert=False, font='', fontFiles=[], height=2, italic=False, name='unnamed TextStim', opacity=1.0, ori=0.0, pos=array([0., 0.]), rgb=array([1., 1., 1.]), text=str(...), units='deg', win=Window(...), wrapWidth=15.0)
4.5411 	EXP 	Created unnamed RadialStim = RadialStim(__class__=<class 'psychopy.visual.radial.RadialStim'>, autoDraw=False, autoLog=True, blendmode='avg', color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, interpolate=False, mask='none', maskParams=None, name='unnamed RadialStim', opacity=1.0, ori=0.0, phase=array([0., 0.]), pos=array([0., 0.]), rgbPedestal=array([0., 0., 0.]), sf=1, size=array([16., 16.]), tex=ndarray(...), texRes=64, units='deg', win=Window(...))
4.5440 	EXP 	Created unnamed RadialStim = RadialStim(__class__=<class 'psychopy.visual.radial.RadialStim'>, autoDraw=False, autoLog=True, blendmode='avg', color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, interpolate=False, mask='none', maskParams=None, name='unnamed RadialStim', opacity=1.0, ori=0.0, phase=array([0., 0.]), pos=array([0., 0.]), rgbPedestal=array([0., 0., 0.]), sf=1, size=array([16., 16.]), tex=ndarray(...), texRes=64, units='deg', win=Window(...))
4.6138 	EXP 	Created unnamed TextStim = TextStim(__class__=<class 'psychopy.visual.text.TextStim'>, alignHoriz='center', alignVert='center', antialias=True, autoLog=True, bold=False, color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, flipHoriz=False, flipVert=False, font='', fontFiles=[], height=2, italic=False, name='unnamed TextStim', opacity=1.0, ori=0.0, pos=array([0., 0.]), rgb=array([1., 1., 1.]), text='Tap your fingers as quickly as possible!', units='deg', win=Window(...), wrapWidth=30)
4.6189 	EXP 	Created unnamed TextStim = TextStim(__class__=<class 'psychopy.visual.text.TextStim'>, alignHoriz='center', alignVert='center', antialias=True, autoLog=True, bold=False, color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, flipHoriz=False, flipVert=False, font='', fontFiles=[], height=2, italic=False, name='unnamed TextStim', opacity=1.0, ori=0.0, pos=array([0., 0.]), rgb=array([1., 1., 1.]), text='+', units='deg', win=Window(...), wrapWidth=15.0)
4.6282 	EXP 	Created unnamed TextStim = TextStim(__class__=<class 'psychopy.visual.text.TextStim'>, alignHoriz='center', alignVert='center', antialias=True, autoLog=True, bold=False, color=array([1., 1., 1.]), colorSpace='rgb', contrast=1.0, depth=0, flipHoriz=False, flipVert=False, font='', fontFiles=[], height=1.0, italic=False, name='unnamed TextStim', opacity=1.0, ori=0.0, pos=array([0., 0.]), rgb=array([1., 1., 1.]), text='Waiting for scanner ...', units='deg', win=Window(...), wrapWidth=15.0)
4.6512 	WARNING 	t of last frame was 226.66ms (=1/4)
5.6078 	DATA 	Keypress: space
5.6232 	WARNING 	t of last frame was 971.99ms (=1/1)
5.6738 	WARNING 	t of last frame was 22.57ms (=1/44)
5.7076 	WARNING 	t of last frame was 22.84ms (=1/43)
5.7577 	WARNING 	Multiple dropped frames have occurred - I'll stop bothering you about them!
44.2046 	DATA 	Keypress: j
298.8002 	EXP 	window1: mouseVisible = True
0:04:53.192592
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x11ac21780>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/text.py", line 177, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method RadialStim.__del__ of <psychopy.visual.radial.RadialStim object at 0x1197e3710>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/radial.py", line 625, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/basevisual.py", line 1001, in clearTextures
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method RadialStim.__del__ of <psychopy.visual.radial.RadialStim object at 0x11afb3c88>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/radial.py", line 625, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/basevisual.py", line 1001, in clearTextures
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x11afc54e0>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/text.py", line 177, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x11afc5e80>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/text.py", line 177, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method TextStim.__del__ of <psychopy.visual.text.TextStim object at 0x11afeada0>>
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/psychopy/visual/text.py", line 177, in __del__
  File "/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
TypeError: 'NoneType' object is not callable
```

**Comment by tsalo** [comment]
We met in November to convert the tasks over to Builder view and most likely resolved this then. I'm keeping it open for now, but will close it once we've completed the Builder-built versions (assuming they work).
